version: '3.4'

services:
  techchallenge.webapi:
    image: ${DOCKER_REGISTRY-}techchallengewebapi
    build:
      context: .
      dockerfile: API/Dockerfile

    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
        - techchallenge.mysql
    networks:
        - techchallenge.network

  techchallenge.mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hipages
      MYSQL_DATABASE: hipages
    ports:
      - "3306:3306"
    volumes:
        - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
        - techchallenge.network

networks:
  techchallenge.network:
    driver: bridge